version: '3.8'

services:
  app:
    build:
      target: development
    environment:
      ENVIRONMENT: development
      LOG_LEVEL: DEBUG
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    command: ["uv", "run", "granian", "--target", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--workers", "1"]

  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: antiques_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password

  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  adminer:
    image: adminer:latest
    container_name: antiques-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - antiques-network
    profiles:
      - dev-tools
